### ISSUE TITLE
Supported project?

### ISSUE THREAD

**Issue by brownad** [lrozema/homebridge-zipato#3]
Hi
Is this still supported, not sure it ever worked correctly. Would be great if it did.  Or someone else takes over

**Comment by derhelle** [comment]
Plugin is working! But it only shows switches and lights....

**Comment by brownad** [comment]
Really? Try and change state and see if it works and it can get correct state

**Comment by derhelle** [comment]
Of course, when I say it works, I use it :-D

**Comment by brownad** [comment]
Cool it’s worth a revisit then. Last time was a waste and a quick uninstall with same results as other issues mentioned

**Comment by brownad** [comment]
Yep the update in the core API fixed the experience closed now 👍
